### PR TITLE
feat: added banner for network-config notices

### PR DESCRIPTION
**Pull request by frazarshad**
This PR adds the `NoticeBanner` in `@agoric/react-components`

image

### CODE REVIEW

**Comment by frazarshad** [comment]
The branch was having issues creating a build.
When tested on my machine, the node process ran out of memory, when i allotted more memory to it, the build passed but the chunk size has increased drastically
@samsiegart 
image

**Review by samsiegart — CHANGES_REQUESTED** [review]
I see there's no issue, I'm just wondering so I can understand the goals better, is there somewhere where this is written down like a doc or something? Most PRs especially features should have issues.

The CF build failed because react-components requires node 18 and it was set up to use 16. I just changed the setting and it builds successfully. However, the test workflow is failing, you just need to run prettier with `yarn format` (or set up your IDE to run prettier automatically on-save).

The bundle size isn't great. That's why I [thought](https://github.com/Agoric/ui-kit/pull/112#pullrequestreview-2088918278) importing react-components might be heavy-handed. How did you allot more memory to the node process? In the UI tutorial it [suggests](https://docs.agoric.com/guides/getting-started/ui-tutorial/agoric-provider.html#dependencies) to do so with `max-old-space-size`. But, it's easier to justify when an app is making full use of the `AgoricProvider` and leap elements. For this I'm tempted to suggest just copying the component into this project because it's pretty simple. That's why I was wondering about an issue, because if the only goal was to add a banner to this dapp I think that approach would've been fine.

**Comment by frazarshad** [comment]
After @samsiegart's comments. made the following updates to the PR:
- removed dependancy on react-components since it drastically increased the build size
- used `networkConfig` that was already being fetched in `chainKit`

**Review by samsiegart — APPROVED** [review]
Looks great thanks!

**Pull request merged**
